steps:
# terraform init -input=false
- name: gcr.io/$PROJECT_ID/terraform
  args:
  - init
  - -input=false
# terraform validate
- name: gcr.io/$PROJECT_ID/terraform
  args:
  - validate
# terraform plan -input=false -out=tfplan
- name: gcr.io/$PROJECT_ID/terraform
  args:
  - plan
  - -input=false
  - -out=tfplan
# terraform apply -auto-approve -input=false tfplan
- name: gcr.io/$PROJECT_ID/terraform
  args:
  - apply
  - -auto-approve
  - -input=false
  - tfplan
  
# steps:

# # initialise Terraform
# - id: terraform-init
#   name: hashicorp/terraform:${_TF_VERSION}
#   args: ['init']
#   dir: ${_DIR}
  
# - id: terraform-plan
#   name: hashicorp/terraform:${_TF_VERSION}
#   args: ['plan']
#   dir: ${_DIR}

# # provision the resources
# - id: terraform-apply
#   name: hashicorp/terraform:${_TF_VERSION}
#   args: ['apply', '--auto-approve']
#   dir: ${_DIR}



